---
- name: Install mongodb
  hosts: all
  become: true
  roles:
    - db
#  tasks:
#    - name: Add an Apt signing key
#      apt_key:
#        keyserver: hkp://keyserver.ubuntu.com:80
#        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
#
#
#    - name: Add MongoDB repository
#      apt_repository:
#        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
#        state: present
#        filename: /etc/apt/sources.list.d/mongodb-org-3.6.list
#
#    - name: Run "apt-get update"
#      apt:
#        update_cache: yes
#
#    - name: Install packages
#      apt:
#        name: "mongodb-org"
#        state: present
#
#    - name: Configure systemctl
#      systemd:
#        name: mongod
#        state: started
#        enabled: yes
