---
- name: Install ruby and bundler
  hosts: all
  become: true
  tasks:
    - name: Run "apt-get update"
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ruby-full
        - ruby-bundler
        - build-essential